README.md

- just a few small spelling edits for documentation
Resolves: patch/sml-rdme-spell-edits

Small Readme Spelling Edits

---

components/Footer/footer.mdx

updated Launchpad title/links

---

components/ClientsList/ClientsList.tsx
pages/pricing/data.yaml

fixes #356
Fixes typos in /pricing

fixes typos in /pricing

---

pages/features/access-requests/index.mdx

Mostly text updates, but I added one link to a blog and not sure if the link should use a relative path. I used a direct link.  You can update directly, or give me a comment and I will do.

Added some Key words to this page to boost SEO

---

pages/about/events/index.mdx

Delete all completed events from next repo in `.../next/pages/about/events/index.mdx` after cross-checking to ensure that event has finished.
FYI: One past event (DevOps Days Nashville) was rescheduled to a future date and will be updated in a future PR.

Delete completed events

---

pages/about/events/index.mdx

- Updated dates for AWS re:Invent to fix Issue [#2320](https://github.com/gravitational/web/issues/2320) and GlueCon to fix Issue [#2319](https://github.com/gravitational/web/issues/2319)

Updated event dates

---

pages/about/events/index.mdx

Added Chaos Carnival event to website per Issue #2338 from web: https://github.com/gravitational/web/issues/2338

Added Chaos Carnival event

---

pages/about/events/index.mdx

- added location to CyberSecurity for Financial Services event

add location to event

---

components/Badge/Badge.stories.tsx
components/Badge/index.ts

- Create storybook entry for `Badge` component
- preview at: `http://localhost:6006/?path=/story/badge--card` after running `yarn storybook`

add Badge to storybook

---

components/Menu/structure.ts

Change top nav to Use Cases

---

.gitmodules
config.json

This PR links v8 docs to `branch/v8` and creates v9 which links to master. 
This PR should be merged alongside the PR release around 6am pacific.

Make latest docs version 8

---

README.md

Credit to @espadolini for crafting this command.

Docker command for previewing local changes

---

pages/security-visionaries-2022/index.mdx

Updates the link for Bruce to point to his website.

Fixes link for Bruce

---

pages/features/multi-factor-auth/index.mdx

Updated this text to be consistent with new messaging guide I am working on with Ev.

Text change

---

pages/about/events/index.mdx

Better late than never https://www.secureworld.io/resources/securing-supply-chain-following-audit-trail

Add SecureWorld Event

---

components/AccessPlane/AccessPlane.tsx
components/AccessPlane/content.ts
components/ProductSection/ProductSection.tsx
pages/index.mdx

Copy edits for homepage except the Developer section.

michael's copy edits for homepage

---

components/GridDisplay/NewProductCard.tsx
components/HeroAnimation2022/AnimationScreens.tsx
components/HeroAnimation2022/MFA.tsx
components/HeroAnimation2022/constants.ts
components/ProductSection/ProductSection.tsx

- updated content on homepage animation to be more accurate
- added call to action on product cards to help usability

Homepage Updates

---

components/HeroAnimation2022/AnimationScreens.tsx
components/Menu/structure.ts

- Removes "Teleport" as a prefix for buttons in "Products" dropdown menu
- improved responsive styles for hero animation

Update to nav and Animation

---

pages/security-visionaries-2022/index.mdx

Updated the time of Troy's webinar to 1pm PT

Updated event time

---

components/AnimationHeader/AnimationHeader.tsx

Fix for https://github.com/gravitational/web/issues/2805 to provide an option for three differenet tracks.

Landing page for 3 different tracks.
